import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { openRefTree, type RefTree } from "../../../src/git/ref-tree.js";
import { applyBaseEvidence } from "../../../src/layers/sql-migrations/base-evidence.js";
import type { BaseExplicitIds, ClassifiedFinding } from "../../../src/layers/sql-migrations/classify.js";
import { sqlMigrationsLayer } from "../../../src/layers/sql-migrations/sql-migrations-layer.js";
import { parseName } from "../../../src/sql/identifiers.js";
import { createRepo, type TestRepo } from "../../helpers/git-repo.js";

const BASE_MIGRATION = [
  'CREATE TABLE dictionaries."PetBreeds" ("Id" int GENERATED BY DEFAULT AS IDENTITY, "Name" text);',
  'INSERT INTO dictionaries."PetBreeds" ("Id", "Name") VALUES (1, \'a\'), (417, \'b\');',
].join("\n");
const NEW_MIGRATION =
  'INSERT INTO dictionaries."PetBreeds" ("Id", "Name") VALUES (418, \'c\'), (496, \'d\');';
const WRITERS = [
  {
    table: "dictionaries.PetBreeds",
    files: ["**/*"],
    patterns: ["new PetBreed(", 'INSERT INTO dictionaries."PetBreeds"'],
  },
];
const ACCEPT = [
  { id: "insert-explicit-id", migration: "0002.sql", basis: "migrations-only", reason: "dictionary rows" },
];
const HEAD =
  "inserts 2 row(s) into dictionaries.PetBreeds with explicit Id 418-496; precondition: production max(Id) < 418, and the identity sequence must continue after 496";
const BASE_IDS =
  "the base migrations insert explicit Id up to 417 into dictionaries.PetBreeds, and never move its identity sequence";

describe("sql-migrations base evidence for explicit-id inserts (issue #130)", () => {
  let repo: TestRepo;
  let tempRoot: string;
  const trees = new Map<string, RefTree>();

  beforeAll(async () => {
    repo = createRepo([
      { files: { "db/0001.sql": BASE_MIGRATION, "src/PetBreed.cs": "class PetBreed {}" }, tag: "clean" },
      { files: { "src/Admin.cs": "// admin\nvar breed = new PetBreed(name);" }, tag: "writer" },
      { files: { "db/0002.sql": NEW_MIGRATION }, tag: "v2" },
    ]);
    tempRoot = await mkdtemp(join(tmpdir(), "compat-sql-base-evidence-"));
    for (const [ref, side] of [
      ["clean", "base"],
      ["writer", "base"],
      ["v2", "revision"],
    ] as const) {
      const opened = await openRefTree({ repoDir: repo.dir, ref, side, tempRoot });
      if (!opened.ok) throw new Error(`cannot open ${ref}`);
      trees.set(ref, opened.value);
    }
  });

  afterAll(async () => {
    repo.cleanup();
    await rm(tempRoot, { recursive: true, force: true });
  });

  const run = async (base: "clean" | "writer", extra: object = {}) => {
    const result = await sqlMigrationsLayer.run({
      config: sqlMigrationsLayer.configSchema.parse({
        sources: [{ name: "db", dialect: "postgres", kind: "folder", path: "db", ...extra }],
      }),
      base: trees.get(base) as RefTree,
      revision: trees.get("v2") as RefTree,
      repoDir: repo.dir,
      tempDir: tempRoot,
      env: process.env,
      log: () => {},
    });
    if (result.status !== "ran") throw new Error(`layer status ${result.status}`);
    return result;
  };

  it("adds the highest explicit id of the base migrations, with the base line as evidence", async () => {
    const result = await run("clean");
    expect(result.findings.map((finding) => [finding.id, finding.class, finding.message])).toEqual([
      ["insert-explicit-id", "needs-action", `${HEAD}; ${BASE_IDS}`],
    ]);
    const base = trees.get("clean") as RefTree;
    expect(result.findings[0]?.evidence[1]).toEqual({
      side: "base",
      ref: "clean",
      commit: base.commit,
      path: "db/0001.sql",
      line: 2,
    });
  });

  it("says no base code outside the migrations writes the table, and lets a migrations-only accept match", async () => {
    const result = await run("clean", { writers: WRITERS, accept: ACCEPT });
    expect(
      result.findings.map((finding) => [finding.class, finding.message, finding.accepted?.reason]),
    ).toEqual([
      [
        "needs-action",
        `${HEAD}; ${BASE_IDS}; no base code outside the migrations matches the writers of dictionaries.PetBreeds`,
        "dictionary rows",
      ],
    ]);
    expect(result.notes).toContain(
      'source "db": accept entry insert-explicit-id in 0002.sql accepted 1 finding(s)',
    );
  });

  it("refuses a migrations-only accept once base code writes the table", async () => {
    const result = await run("writer", { writers: WRITERS, accept: ACCEPT });
    expect(result.findings.map((finding) => [finding.message, finding.accepted])).toEqual([
      [
        `${HEAD}; ${BASE_IDS}; base code outside the migrations writes dictionaries.PetBreeds (src/Admin.cs:2)`,
        undefined,
      ],
    ]);
    expect(result.findings[0]?.evidence.at(-1)).toMatchObject({
      side: "base",
      path: "src/Admin.cs",
      line: 2,
    });
    expect(result.notes).toContain(
      'source "db": accept entry insert-explicit-id in 0002.sql accepted nothing; its basis migrations-only does not hold: base code writes dictionaries.PetBreeds (src/Admin.cs:2)',
    );
  });

  it("refuses a migrations-only accept without configured writers", async () => {
    const result = await run("clean", { accept: ACCEPT });
    expect(result.findings[0]?.accepted).toBeUndefined();
    expect(result.notes).toContain(
      'source "db": accept entry insert-explicit-id in 0002.sql accepted nothing; its basis migrations-only does not hold: no writers are configured for dictionaries.PetBreeds',
    );
  });

  it("leaves an insert settled by the preconditions command without base evidence", async () => {
    const result = await run("clean", { preconditions: { run: "printf 'dictionaries.PetBreeds\\t500\\n'" } });
    expect(result.findings.map((finding) => [finding.class, finding.message])).toEqual([
      ["breaking", `${HEAD}; production max(Id) = 500 >= 418, the insert collides (preconditions command)`],
    ]);
  });
});

describe("applyBaseEvidence", () => {
  const BASE = { side: "base" as const, ref: "v1", commit: "b".repeat(40) };
  const insert = (range: { first: number; last: number } | null): ClassifiedFinding => ({
    migration: "0002",
    object: "T",
    finding: {
      layer: "sql-migrations",
      scope: "db",
      id: "insert-explicit-id",
      subject: "0002: T",
      class: "needs-action",
      message: "m",
      evidence: [],
    },
    explicitIds: {
      table: parseName("T", "postgres"),
      ids: { column: "Id", rows: 1, range },
      isSequenceMoved: false,
    },
  });
  const apply = (item: ClassifiedFinding, baseIds: BaseExplicitIds | undefined) => {
    applyBaseEvidence([item], {
      baseIds: new Map(baseIds ? [["public.t", baseIds]] : []),
      writers: new Map([["public.t", null]]),
      base: BASE,
    });
    return [item.finding.message, item.basis];
  };
  const reset = { path: "db/0001.sql", line: 3 };

  it.each([
    [
      "base ids at or above the first new id",
      insert({ first: 5, last: 6 }),
      { max: { id: 5, path: "db/0001.sql", line: 1 }, hasUnreadIds: false, sequenceReset: reset },
      "m; the base migrations insert explicit Id up to 5 into T, and move its identity sequence; no base code outside the migrations matches the writers of T",
      { holds: false, reason: "the base migrations insert id 5 into T, not below 5" },
    ],
    [
      "base ids that cannot be read",
      insert({ first: 5, last: 6 }),
      { max: null, hasUnreadIds: true, sequenceReset: null },
      "m; the base migrations insert explicit ids into T that cannot be read, and never move its identity sequence; no base code outside the migrations matches the writers of T",
      { holds: false, reason: "the base migrations insert ids into T that cannot be read" },
    ],
    [
      "no base inserts",
      insert({ first: 5, last: 6 }),
      undefined,
      "m; the base migrations insert no explicit ids into T; no base code outside the migrations matches the writers of T",
      { holds: false, reason: "the base migrations insert no explicit ids into T" },
    ],
    [
      "new ids that cannot be read",
      insert(null),
      { max: { id: 4, path: "db/0001.sql", line: 1 }, hasUnreadIds: false, sequenceReset: null },
      "m; the base migrations insert explicit Id up to 4 into T, and never move its identity sequence; no base code outside the migrations matches the writers of T",
      { holds: false, reason: "the inserted ids cannot be read" },
    ],
    [
      "base ids below the new ones",
      insert({ first: 5, last: 6 }),
      { max: { id: 4, path: "db/0001.sql", line: 1 }, hasUnreadIds: false, sequenceReset: reset },
      "m; the base migrations insert explicit Id up to 4 into T, and move its identity sequence; no base code outside the migrations matches the writers of T",
      { holds: true },
    ],
  ])("describes %s", (_name, item, baseIds, message, basis) => {
    expect(apply(item, baseIds)).toEqual([message, basis]);
  });
});
