-- Shape of `dotnet ef migrations script --idempotent` output, EF Core 8 with Npgsql.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901000000_Init') THEN
    CREATE TABLE "Breeds" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Breeds" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901000000_Init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901000000_Init', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'system') THEN
            CREATE SCHEMA system;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
    CREATE TABLE system."FeatureFlags" (
        "Id" uuid NOT NULL,
        "Key" character varying(100) NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_FeatureFlags" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
    CREATE UNIQUE INDEX "IX_FeatureFlags_Key" ON system."FeatureFlags" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261001000000_AddFeatureFlags', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'notifications') THEN
            CREATE SCHEMA notifications;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    CREATE TABLE notifications."NotificationBroadcasts" (
        "Id" uuid NOT NULL,
        "BreedId" integer,
        "Title" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_NotificationBroadcasts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NotificationBroadcasts_Breeds_BreedId" FOREIGN KEY ("BreedId") REFERENCES "Breeds" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    CREATE INDEX "IX_NotificationBroadcasts_BreedId" ON notifications."NotificationBroadcasts" ("BreedId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    ALTER TABLE notifications."NotificationBroadcasts" ADD CONSTRAINT "AK_NotificationBroadcasts_Title" UNIQUE ("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261002000000_AddNotificationBroadcasts', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (418, 'Breed 418');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (419, 'Breed 419');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (420, 'Breed 420');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (421, 'Breed 421');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (422, 'Breed 422');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (423, 'Breed 423');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (424, 'Breed 424');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (425, 'Breed 425');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (426, 'Breed 426');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (427, 'Breed 427');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (428, 'Breed 428');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (429, 'Breed 429');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (430, 'Breed 430');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (431, 'Breed 431');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (432, 'Breed 432');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (433, 'Breed 433');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (434, 'Breed 434');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (435, 'Breed 435');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (436, 'Breed 436');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (437, 'Breed 437');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (438, 'Breed 438');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (439, 'Breed 439');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (440, 'Breed 440');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (441, 'Breed 441');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (442, 'Breed 442');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (443, 'Breed 443');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (444, 'Breed 444');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (445, 'Breed 445');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (446, 'Breed 446');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (447, 'Breed 447');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (448, 'Breed 448');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (449, 'Breed 449');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (450, 'Breed 450');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (451, 'Breed 451');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (452, 'Breed 452');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (453, 'Breed 453');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (454, 'Breed 454');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (455, 'Breed 455');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (456, 'Breed 456');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (457, 'Breed 457');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (458, 'Breed 458');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (459, 'Breed 459');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (460, 'Breed 460');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (461, 'Breed 461');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (462, 'Breed 462');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (463, 'Breed 463');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (464, 'Breed 464');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (465, 'Breed 465');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (466, 'Breed 466');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (467, 'Breed 467');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (468, 'Breed 468');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (469, 'Breed 469');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (470, 'Breed 470');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (471, 'Breed 471');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (472, 'Breed 472');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (473, 'Breed 473');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (474, 'Breed 474');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (475, 'Breed 475');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (476, 'Breed 476');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (477, 'Breed 477');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (478, 'Breed 478');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (479, 'Breed 479');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (480, 'Breed 480');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (481, 'Breed 481');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (482, 'Breed 482');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (483, 'Breed 483');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (484, 'Breed 484');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (485, 'Breed 485');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (486, 'Breed 486');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (487, 'Breed 487');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (488, 'Breed 488');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (489, 'Breed 489');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (490, 'Breed 490');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (491, 'Breed 491');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (492, 'Breed 492');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (493, 'Breed 493');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (494, 'Breed 494');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (495, 'Breed 495');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "Breeds" ("Id", "Name")
    VALUES (496, 'Breed 496');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005073152_AddMissingPetBreeds') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261005073152_AddMissingPetBreeds', '8.0.10');
    END IF;
END $EF$;
COMMIT;
