-- Shape of `dotnet ef migrations script --idempotent` output, EF Core 8 with Npgsql.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901000000_Init') THEN
    CREATE TABLE "Breeds" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Breeds" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901000000_Init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901000000_Init', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'system') THEN
            CREATE SCHEMA system;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
    CREATE TABLE system."FeatureFlags" (
        "Id" uuid NOT NULL,
        "Key" character varying(100) NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_FeatureFlags" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
    CREATE UNIQUE INDEX "IX_FeatureFlags_Key" ON system."FeatureFlags" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001000000_AddFeatureFlags') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261001000000_AddFeatureFlags', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'notifications') THEN
            CREATE SCHEMA notifications;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    CREATE TABLE notifications."NotificationBroadcasts" (
        "Id" uuid NOT NULL,
        "BreedId" integer,
        "Title" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_NotificationBroadcasts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NotificationBroadcasts_Breeds_BreedId" FOREIGN KEY ("BreedId") REFERENCES "Breeds" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    CREATE INDEX "IX_NotificationBroadcasts_BreedId" ON notifications."NotificationBroadcasts" ("BreedId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    ALTER TABLE notifications."NotificationBroadcasts" ADD CONSTRAINT "AK_NotificationBroadcasts_Title" UNIQUE ("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261002000000_AddNotificationBroadcasts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261002000000_AddNotificationBroadcasts', '8.0.10');
    END IF;
END $EF$;
COMMIT;
